# Generated by Django 2.1.5 on 2019-01-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('MaxMarks', models.IntegerField()),
                ('TimeDuration', models.IntegerField()),
                ('PosMarks', models.IntegerField()),
                ('NegMarks', models.IntegerField()),
            ],
        ),
    ]
