# Generated by Django 2.1.5 on 2019-02-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=255)),
                ('MaxMarks', models.IntegerField()),
                ('TimeDuration', models.IntegerField()),
                ('PosMarks', models.IntegerField()),
                ('NegMarks', models.IntegerField()),
                ('inputText', models.TextField()),
                ('mimeType', models.CharField(max_length=50)),
                ('InputTextFile', models.FileField(blank=True, null=True, upload_to='Test.TestM/inputText/TestName/mimeType')),
            ],
        ),
    ]
