# Generated by Django 2.1.5 on 2019-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testm',
            name='inputText',
        ),
        migrations.RemoveField(
            model_name='testm',
            name='mimeType',
        ),
        migrations.AlterField(
            model_name='testm',
            name='InputTextFile',
            field=models.FileField(blank=True, null=True, upload_to='Test/TestName/'),
        ),
    ]
