# Generated by Django 2.1.5 on 2019-01-30 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_testm_inputtextfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testm',
            name='FileName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testm',
            name='mimeType',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testm',
            name='InputTextFile',
            field=models.FileField(blank=True, null=True, upload_to='Test.TestM/InputTextFile/FileName/mimeType'),
        ),
        migrations.AlterField(
            model_name='testm',
            name='TestName',
            field=models.CharField(max_length=255),
        ),
    ]
