# Generated by Django 2.1.5 on 2019-01-30 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20190130_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testm',
            name='FileName',
        ),
        migrations.RemoveField(
            model_name='testm',
            name='mimeType',
        ),
        migrations.AlterField(
            model_name='testm',
            name='InputTextFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
